@startuml
set separator none
title Template

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("ActenoraApplication.ActenoraApplication_boundary", "ActenoraApplication", $tags="") {
  Component(ActenoraApplication.ActenoraApplication.SharedKernel, "Shared Kernel", $techn="Module", $descr="", $tags="", $link="")
  Component(ActenoraApplication.ActenoraApplication.Template, "Template", $techn="Module", $descr="", $tags="", $link="")
}

Rel(ActenoraApplication.ActenoraApplication.Template, ActenoraApplication.ActenoraApplication.SharedKernel, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml