@startuml
set separator none
title Security

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("ActenoraApplication.ActenoraApplication_boundary", "ActenoraApplication", $tags="") {
  Component(ActenoraApplication.ActenoraApplication.Security, "Security", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml