@startuml
set separator none
title Identity

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("ActenoraApplication.ActenoraApplication_boundary", "ActenoraApplication", $tags="") {
  Component(ActenoraApplication.ActenoraApplication.SharedKernel, "Shared Kernel", $techn="Module", $descr="", $tags="", $link="")
  Component(ActenoraApplication.ActenoraApplication.Identity, "Identity", $techn="Module", $descr="", $tags="", $link="")
}

Rel(ActenoraApplication.ActenoraApplication.Identity, ActenoraApplication.ActenoraApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml